title: Home
# description: description
email: howepa287@gmail.com
baseurl: "" 
url: "" 
author: howepa

# social:
github: howepa

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
# theme: 'jekyll-theme-persephone'
remote_theme: erlzhang/jekyll-theme-persephone
logo: /img/homepage.svg
markdown: kramdown
