title: Home
# description: description
email: howepa287@gmail.com
baseurl: "" 
url: "" 
author: howepa
social:
  github: howepa

remote_theme: rundocs/jekyll-rtd-theme

markdown: kramdown

readme_index:
  with_frontmatter: true

plugins:
  - jekyll-remote-theme