title: Home
# description: description
email: howepa287@gmail.com
baseurl: "" 
url: "" 
author: howepa

# social:
github: howepa

# theme: 'jekyll-theme-persephone'
remote_theme: "erlzhang/jekyll-theme-persephone"
logo: /img/homepage.svg
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-remote-theme